@startuml

interface WeatherProvider {
    + obtenerClimaActual(Ciudad): Clima
}

class WeatherApiClient implements WeatherProvider {
    + obtenerClimaActual(Ciudad): Clima
}

class EvaluadorClimatico {
    - condiciones: Set<CondicionDeAlerta>
}

interface CondicionDeAlerta {
    + evaluar(clima: Clima): Optional<Alerta>
}

class SofocacionAmbiental implements CondicionDeAlerta {
    - temperatura: double
    - humedad: int

    + evaluar(clima: Clima): Optional<Alerta>
}

class Clima {
    - id: long
    - pais: String
    - ciudad: String
    - fechaYHora: String
    - temperatura: double
    - humedad: int
}

class Alerta {
    - id: long
}

EvaluadorClimatico --> "*" CondicionDeAlerta
WeatherProvider ..> Clima
CondicionDeAlerta ..> Alerta
@enduml