@startuml

interface WeatherProvider {
    + obtenerClimaActual(Ciudad): Clima
}

class WeatherApiClient implements WeatherProvider {
    + obtenerClimaActual(Ciudad): Clima
}

class EvaluadorClimático {
    - condiciones: Set<CondiciónDeAlerta>

    + evaluar(clima: Clima): List<Alerta>
}

interface CondiciónDeAlerta {
    + evaluar(clima: Clima): Optional<Alerta>
}

class SofocaciónAmbiental implements CondiciónDeAlerta {
    - temperatura: double
    - humedad: int

    + evaluar(clima: Clima): Optional<Alerta>
}

class Clima {
    - id: Long
    - pais: String
    - ciudad: String
    - fechaYHora: LocalDateTime
    - temperatura: Double
    - humedad: Integer
}

class Alerta {
    - id: Long
    - ciudad: String
    - nombre: String
    - fechaYHora: LocalDateTime
}

class Interesado {
    - id: Long
    - nombre: String
    - email: String
}

interface Notificador {
    + enviarAlerta(destinatario, cuerpo)
}

class EmailNotificador implements Notificador {
    + enviarAlerta(destinatario, cuerpo)
}


EvaluadorClimático --> "*" CondiciónDeAlerta
EvaluadorClimático ..left> Alerta
WeatherProvider ..right> Clima

@enduml